from .AuthService import AuthService
from .DashboardService import DashboardService
from .DefectService import DefectService
from .KategoriService import KategoriService
from .LaporanService import LaporanService
from .PencapaianService import PencapaianService
from .ProdukService import ProdukService
from .ProduksiService import ProduksiService
from .TargetService import TargetService
from .UserDataLocal import UserDataLocal
